---
language: ruby
rvm:
- 2.3.3
script:
- bundle exec rake run_tests
env:
  global:
  - secure: |-
      UgkY7PDsbBfq3Ukyzb6VIWXY6zd7s8bJMLOkkQ7RK7huwl68jfeYSpLwJ6Rm
      2qVaYj84YDmSwr6ed6Fk2C+1IviqlN4NkJ0c9JtibHHOVOxBB8Y+dm17DFPp
      jsIOOUB/NduVNOlIKMCwCiXFEPBTwhiWLFGEkE4HHLk3HnxHaj8=
  - secure: |-
      agxJsFr30M/dvbj2+tqBHmklouxk8+PRO+DBJOEWdGBxjJVis0kcDsFCp3sa
      V0TqnS/+7ExVOjez4b6r9NSNrBmxhQuVYEr1Wsk96CE1B16Y1XsCImvIooxl
      KPJWYy2szbex7i8ibCkA7w0Yvb8QhmHMLAa3aVtteEOAGULyCr4=
  - secure: |-
      jqHIRzqNXdFT/QIksVfMYFSHAiFKOY16hNjyWQr8g7g/DuFAIdjO7zhCqK7H
      bDQ0RDqw84MNnrCFdctvxE6n4nHO3guM4BYLSAENflXVAugzlve5BTFRZfbz
      qJ5cboa3VSwZeks/PYoIIwbaFCpVlMulEMRgKl0YjDs/y9RhcYo=
